# Forked from MIT licensed repo: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/36cbb8aa21051b00bc753abde5be781d5203821f/.github/workflows/ci.yml
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare (pnpm, Node, install)
        uses: ./.github/actions/prepare

      - name: Build site
        run: pnpm build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm lint:check
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm format:list
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm run test
  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm tsc

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write
